# Generated by Django 3.1.3 on 2020-11-16 12:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('zipname', models.CharField(max_length=100)),
                ('user_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
